sudo: false
dist: trusty
language: node_js
# node version is specified using the .nvmrc file
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload

